{
    'name': 'Operation',
    'author': 'Hamada Kamal ITSS',
    'depends': ['fleet','mail','account'],
    'license': 'LGPL-3',
    'sequence': 1,
    'version': '16.0.0.1',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'report/report_counter.xml',
        'wizard/add_driver_wiz.xml',
        'wizard/receive_vehicle_wiz.xml',
        'wizard/add_damage_wiz.xml',
        'wizard/return_available_wiz.xml',
        'wizard/send_car_wiz.xml',
        'views/fleet_vehicle.xml',
        'views/fleet_state.xml',
        'views/dashboard.xml',
        'views/operational_center.xml',
        'views/hall.xml',
        'views/counter.xml',
        'views/product_product.xml',
        'views/city.xml',
        'views/pricing.xml',
        'views/menus.xml',
    ],
}
